//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface Appointment {
    birthDate?: string | null;
    contactId?: string | null;
    duration: number;
    firstName?: string | null;
    id: string;
    lastName?: string | null;
    payment: number;
    paymentDate?: string | null;
    phoneNumber?: string | null;
    price: number;
    startDate: string;
    state: number;
    title?: string | null;
    type?: string | null;
    typeId?: string | null;
    backgroundColor?: string | null;
    documents: BinaryDocument[];
    foreColor?: string | null;
}

export interface AppointmentInformation {
    birthDate?: string | null;
    contactId?: string | null;
    duration: number;
    firstName?: string | null;
    id: string;
    lastName?: string | null;
    payment: number;
    paymentDate?: string | null;
    phoneNumber?: string | null;
    price: number;
    startDate: string;
    state: number;
    title?: string | null;
    type?: string | null;
    typeId?: string | null;
}

export interface BinaryDocument {
    date: string;
    fileName: string;
    id: string;
    title: string;
}

export interface Contact {
    birthDate?: string | null;
    city?: string | null;
    country?: string | null;
    email?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    mobileNumber?: string | null;
    number?: string | null;
    phoneNumber?: string | null;
    street?: string | null;
    title?: string | null;
    zipCode?: string | null;
    id: string;
}

export interface DocumentConfiguration {
    body?: string | null;
    name?: string | null;
    title?: string | null;
    id: string;
}

export interface DocumentRequest {
    documentId: string;
    appointmentId: string;
}

export interface DownloadReference {
    id: string;
}

export interface Filter {
    field: string;
    value: any;
    operator: string;
}

export interface Forecast {
    title?: string | null;
    id: string;
}

export interface ForecastInformation {
    id: string;
    title: string;
}

export interface Setting {
    id: string;
    value: string;
}

export interface Tariff {
    price: number;
    defaultDuration: number;
    id: string;
    name: string;
    backgroundColor?: string | null;
    foreColor?: string | null;
}

export interface UpsertResult {
    id?: string | null;
}

export interface UserInformation {
    isAuthenticated: boolean;
    name: string;
    organization: string;
}