name: CD - Nightly

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  api:
    uses: ./.github/workflows/cd-docker.yml
    with:
      dockerFile: ./Prism.ProAssistant.Api/Dockerfile
      imageTag: api
      workingDirectory: src/api/
      isProduction: false
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  
  web:
    uses: ./.github/workflows/cd-docker.yml
    with:
      dockerFile: ./Dockerfile
      imageTag: web
      workingDirectory: src/web/
      isProduction: false
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}