name: CD

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:  
  web:
    uses: ./.github/workflows/cd-docker.yml
    with:
      dockerFile: ./Dockerfile
      imageTag: web
      workingDirectory: ./web
      isProduction: true
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
