name: CD

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  api:
    uses: ./.github/workflows/cd-docker.yml
    with:
      dockerFile: ./Prism.ProAssistant.Api/Dockerfile
      imageTag: api
      workingDirectory: src/api/
      isProduction: true
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  
  web:
    uses: ./.github/workflows/cd-docker.yml
    with:
      dockerFile: ./Dockerfile
      imageTag: web
      workingDirectory: src/web/
      isProduction: true
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  
  deploy:
    needs: [api, web]
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST \
          -H "Authorization: Bearer ${{secrets.PRISM_ACCESS_TOKEN}}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/prism-be/pro-assistant-deploy/actions/workflows/deploy.yml/dispatches \
          -d '{"ref": "master"}'
