name: CI
on:
  push:
    branches:
      - main
      - feature/*
      - bugfix/*
      - hotfix/*
      - fix/*
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency: ci-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout Sources
      - uses: actions/setup-node@v2
        name: Setup Node
        with:
          node-version: '18'
      - name: Cache yarn cache
        uses: actions/cache@v3
        with:
          path: |
            **/.yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Cache Yarn PnP
        uses: actions/cache@v3
        with:
          path: ./.pnp.cjs
          key: ${{ runner.os }}-yarn-pnp-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies
        run: |
          corepack enable
          corepack prepare yarn@stable --activate
          yarn install --immutable
      - name: Build the application
        run: |
          yarn build