name: CI - Front

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/web/**'
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - 'src/web/**'

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Extract Version
        uses: damienaicheh/extract-version-from-tag-action@v1.0.0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: ./src/web/yarn.lock
      
      - name: Cache Modules
        uses: actions/cache@v2
        with:
          path: './src/web/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('./src/web/yarn.lock') }}
      
      - name: Install Packages
        working-directory: ./src/web
        run: yarn install --frozen-lockfile

      - name: Build Project
        working-directory: ./src/web
        run: yarn build
        
#      - name: Run Unit Tests
#        working-directory: ./src/web
#        run: yarn jest

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: ./src/web
          args: >
            -Dsonar.projectVersion=${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}.${{ env.NUMBER_OF_COMMITS_SINCE_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}