name: CI
on:
  push:
    branches:
      - main
      - feature/*
      - bugfix/*
      - hotfix/*
      - fix/*
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency: ci-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout Sources
      - uses: actions/setup-node@v2
        name: Setup Node
        with:
          node-version: '18'
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/.yarn
            ${{ github.workspace }}/.pnp.cjs
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-deps-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies
        run: |
          corepack enable
          corepack prepare yarn@stable --activate
          yarn install --immutable
      - name: Build the application
        run: |
          yarn build
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: ./
          args: >
            -Dsonar.projectVersion=${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}.${{ env.NUMBER_OF_COMMITS_SINCE_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}