name: CI
on:
  push:
    branches:
      - main
    paths:
      - 'web/**'
  pull_request:
    branches:
      - main
    paths:
      - 'web/**'
  workflow_dispatch:

concurrency: ci-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout Sources
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        name: Setup Node
        with:
          node-version: '18'
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/web/.yarn
            ${{ github.workspace }}/web/.pnp.cjs
            ${{ github.workspace }}/web/.next/cache
          key: ${{ runner.os }}-deps-${{ hashFiles('**/web/yarn.lock') }}
      - name: Install Dependencies
        working-directory: ./web
        run: |
          corepack enable
          corepack prepare yarn@stable --activate
          yarn install --immutable
      - name: Build the application
        working-directory: ./web
        run: |
          yarn build
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: ./web
          args: >
            -Dsonar.projectVersion=${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}.${{ env.NUMBER_OF_COMMITS_SINCE_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}