name: CI - Services

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'api/**'
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - 'api/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Extract Version
        uses: damienaicheh/extract-version-from-tag-action@v1.0.0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.x

      - name: Trick for Sonar
        run: rm -f ./sonar-project.properties

      - name: Build and Analyze
        uses: highbyte/sonarscan-dotnet@v2.2.1
        with:
          sonarProjectKey: prism-be_pro-assistant-api
          sonarProjectName: pro-assistant-api
          sonarOrganization: prism-be
          dotnetBuildArguments: ./api
          dotnetTestArguments: ./api --logger trx --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
          sonarBeginArguments: /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml" -d:sonar.cs.vstest.reportsPaths="**/TestResults/*.trx" /v:${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}.${{ env.NUMBER_OF_COMMITS_SINCE_TAG }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
